### ISSUE TITLE
Distribute the app using Desktop Bridge

### ISSUE THREAD

**Issue by martinsuchan** [sandord/DpiGonzales#11]
Hi,
thanks for the app, it helps a lot when using Windows 10 on both 4K laptop screen and FullHD 24" LCD.
Here's an idea how to distribute the app - using the **Windows Desktop Bridge**. It solves lots of issues like installer, updates, autostart, uninstall, etc.:
https://developer.microsoft.com/en-us/windows/bridges/desktop

**Comment by sandord** [comment]
That is an interesting suggestion. I don't have much time to look into this on short notice however. 

Besides, I think the app needs some more testing and explanation on how it works. For example, if you've increased your mouse speed in Windows beyond the default setting before 'installing' the app, you might be surprised that the mouse now moves much faster on the high DPI screen than would be disirable. In other words, one should leave the Windows mouse speed setting to it's default before using the app. I guess this can cause confusion if you don't understand this.

**Comment by sandord** [comment]
Closing this issue because the app is not actively developed anymore (there's hardly any use for it since Microsoft fixed the multi-monitor pointer speed variances).
