### ISSUE TITLE
Application crashes immediately after opening

### ISSUE THREAD

**Issue by dan-cohn** [sandord/DpiGonzales#15]
I'm on the latest version (v1.0.32). When I run the .exe, it briefly starts (appears in task manager) and then disappears. I checked the Event Viewer and found the following errors:

--- .NET Runtime error ---
Application: DpiGonzales.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at DpiGonzales.App..cctor()

Exception Info: System.TypeInitializationException
   at DpiGonzales.App.set_RefreshRate(Int32)
   at DpiGonzales.App..ctor()
   at DpiGonzales.App.Main()

--- Application Error ---
Faulting application name: DpiGonzales.exe, version: 1.0.32.0, time stamp: 0x5963a875
Faulting module name: KERNELBASE.dll, version: 10.0.14393.1378, time stamp: 0x594a13be
Exception code: 0xe0434352
Fault offset: 0x000da9f2
Faulting process id: 0x369c
Faulting application start time: 0x01d3030c8bcf56db
Faulting application path: C:\Program Files\Mouse DPI Speed Fix\DpiGonzales.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 1cc1b266-2b35-48d8-9fe8-2eeb3e4ab422
Faulting package full name: 
Faulting package-relative application ID: 

[AppCrashReport.zip](https://github.com/sandord/DpiGonzales/files/1167512/AppCrashReport.zip)

**Comment by sandord** [comment]
Can you try v1.0.33 and see if you get more information in the event log or the `DpiGonzales.log` file now?

**Comment by dan-cohn** [comment]
Will do!

**Comment by dan-cohn** [comment]
It's working now. And I'm an idiot because I forgot to copy some of the files from the zip archive into the program folder.

**Comment by sandord** [comment]
No sweat! Glad it works now.
