### ISSUE TITLE
Laggy mouse on high-dpi monitor

### ISSUE THREAD

**Issue by dhoepelman** [sandord/DpiGonzales#19]
Thanks for the awesome tool! this should really be something windows natively fixes

Unfortunately, on my high-dpi display, this tool causes the cursor to become "laggy", or "jump" from point to point instead of going much smoother. At first, I thought it might be the refresh rate but it seems much lower than that, maybe 10-20 "fps".

Setting the refresh rate to 120 makes this a bit better, but it is still noticeably laggier than on my normal-dpi display. Manually altering the config file to set it to 400 is even better (might be placebo), but unfortunately not a total fix.

Is there anything that can be done to alleviate this?

**Comment by sandord** [comment]
I have no idea what's going on on your system. As long as the pointer stays on the same display, DpiGonzales is making no changes to the mouse settings so I don't see how that could result in what you're describing. Perhaps you can make a small video using your phone camera or something to demonstrate the effect?

The refresh rate setting is actually referring to the rate at which DpiGonzales checks whether the mouse pointer has moved to another display. Using a very low setting means that the pointer speed may be adjusted a little later than you see the pointer enter a display. So, a setting of 60 Hz should be fine for most of you, even for those using display modes with higher refresh rates.

**Comment by sandord** [comment]
Oh, I forgot to ask whether you updated the `.config` file in the directory you copied the files to or the one in `C:\Users\?\AppData\Local\DpiGonzales\DpiGonzales.exe_Url_?\?\`? Only the latter will affect your settings, the other one contains default values only.

**Comment by dhoepelman** [comment]
Yes, I edited the config in `%LocalAppData%\DpiConzales`.

Your explanation seems sensible, it might have nothing to do with DpiGonzales then (might just be more noticeable because without the cursor is so slow), I'll investigate some further. Refresh rate influencing things might then be coincidence or I might be mistaken. 

I'll investigate some further, but for now I'll assume it has nothing to do with DpiGonzales, thanks :)

**Comment by dhoepelman** [comment]
Turns out the high-dpi monitor was on 30Hz. Whoops, sorry for bothering you.

**Comment by sandord** [comment]
No problem, glad you fixed your refresh rate problem. I know how terrible it is to work on 30Hz.
