### ISSUE TITLE
Not working with android tablet as virtual display with precision touchpad

### ISSUE THREAD

**Issue by ackvf** [sandord/DpiGonzales#21]
# see bottom for update

_My problem may not be valid, since I have precision touchpad. See at the bottom._

# original report

My setup _(touchpad)_
1: `DELL XPS 13.3", 16:9, 3840x2160 px, scaling 150%`
2: `Lenovo Yoga Tablet 3 10.1", 16:10, 2560x1600 px, scaling 125%`

If my understanding of windows scaling is correct, when interpolated to 1:1 scaling, the displays feel like
1: `13.3", 2560x1440 px`
2: `10.1", 2048x1280 px`

which then, with the smaller screen extrapolated to the size of larger should feel more/less the same for the values of my initial setup.
2: `10.1" 16:10` -> `13.3" 16:9` = `2696x1516 px` 
_only a 5% difference to perceived resolution 2560x1440 px of the main display (1)_

My setup
![photo](https://user-images.githubusercontent.com/2313018/52633640-5ae67b00-2ec5-11e9-8b8f-5414d8e75b52.jpg)

Screenshot from OS' perspective
![screenshot](https://user-images.githubusercontent.com/2313018/52633824-d6e0c300-2ec5-11e9-9e84-f0500c9217fa.jpg)

That window in the middle is _ScreenToGif_ and here comes the output with no perceived difference with the gonzales app on or off.

Mouse speed (windows)
![mouse-speed-win](https://user-images.githubusercontent.com/2313018/52633671-72bdff00-2ec5-11e9-88ab-8a21d0b9c41f.gif)

Mouse speed (gonzales)
![mouse-speed-gonzales](https://user-images.githubusercontent.com/2313018/52633679-78b3e000-2ec5-11e9-8b5d-45c12cf04df3.gif)

Gonzales config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
      <section name="DpiGonzales.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
    </sectionGroup>
  </configSections>
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true">
    <targets>
      <target name="logfile" xsi:type="File" fileName="DpiGonzales.log" />
    </targets>
    <rules>
      <logger name="*" minlevel="Info" writeTo="logfile" />
    </rules>
  </nlog>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6"/>
  </startup>
  <userSettings>
    <DpiGonzales.Properties.Settings>
      <setting name="MouseSpeedToDisplayDpiRatio" serializeAs="String">
        <value>16</value>
      </setting>
      <setting name="RefreshRate" serializeAs="String">
        <value>60</value>
      </setting>
    </DpiGonzales.Properties.Settings>
  </userSettings>
</configuration>
```

# /update
The gonzolas indeed changes the mouse speed
![image](https://user-images.githubusercontent.com/2313018/52635253-b286e580-2ec9-11e9-89df-a57ec1c0a66a.png)

However, my computer has a different setting for touchpad speed.
![image](https://user-images.githubusercontent.com/2313018/52635207-8ec39f80-2ec9-11e9-92a2-32e3c7d7faba.png)

Is it possible for your app to handle this or am I out of luck?

**Comment by sandord** [comment]
Thanks for the exemplary detailed report.

I've done a quick search and it seems that Microsoft hasn't exposed an API for precision touchpads yet. There is a registry key but that is only applied on reboot.

So, basically your out of luck until the precision touchpad APIs appear.

Since Microsoft has fixed the multi-monitor pointer speed variances for mice since Windows 10 build 16273 (or somewhere close), there's hardly any need for DPI Gonzales anymore so you'll probably have to create a fork and implement precision touchpad support yourself.

**Comment by ackvf** [comment]
Do you, by any chance, know where can I submit a bug/feature request to Microsoft about the Precision touchpads?

PS: I believe you can close this issue, cheers!

**Comment by sandord** [comment]
> Do you, by any chance, know where can I submit a bug/feature request to Microsoft about the Precision touchpads?

I haven't found such place but generally, the Windows Feedback Hub and [Windows developer feedback site at uservoice.com](https://wpdev.uservoice.com/) would be the place to go to.
